  version: '3'
  services:
    n8n:
      image: custom-n8n
      ports:
        - "5678:5678"
      environment:
        - N8N_BASIC_AUTH_ACTIVE=true
        - N8N_BASIC_AUTH_USER=admin
        - N8N_BASIC_AUTH_PASSWORD=yourpassword
      volumes:
        - ~/.n8n:/home/node/.n8n
        - ${N8N_SCRIPT}:/home/node/script_60s_50usr5rup
        - ${N8N_RESULT}:/home/node/result_60s_50usr5rup
        - ${IBANK_UAT}:/home/node/scripts/ibank-uat
        - ${IBANK_SIT}:/home/node/scripts/ibank-sit
        - ${IBANK_STG}:/home/node/scripts/ibank-stg